import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import Link from 'next/link';

const productData: Record<string, any> = {
  'xtool-f1-ultra': {
      name: 'xTool F1 Ultra',
          tagline: 'May khac laser toc do cao nhat the gioi',
              price: 'Lien he bao gia',
                  img: 'https://cdn.shopify.com/s/files/1/0467/7985/9095/files/mk-20236shouyedaohanglan_us_pc_pc-22-f1ultra_3632-3562.webp',
                      specs: [
                            { label: 'Toc do khac', value: '10.000 mm/s' },
                                  { label: 'Nguon laser', value: 'Diode Blue + Infrared' },
                                        { label: 'Cong suat', value: '20W / 2W IR' },
                                            ],
                                                desc: 'xTool F1 Ultra la may khac laser galvo nhanh nhat the gioi, ket hop hai nguon sang Diode va Infrared.',
                                                    features: ['Buong kin chong buc xa', 'Camera 48MP tich hop', 'AI tu dong nhan vat lieu'],
                                                      },
                                                        'xtool-d1-pro': {
                                                            name: 'xTool D1 Pro',
                                                                tagline: 'May khac laser di dong da dung',
                                                                    price: 'Tu 8.900.000d',
                                                                        img: 'https://cdn.shopify.com/s/files/1/0467/7985/9095/files/D1Pro-product.webp',
                                                                            specs: [
                                                                                  { label: 'Cong suat laser', value: '10W / 20W / 40W' },
                                                                                        { label: 'Toc do toi da', value: '400 mm/s' },
                                                                                              { label: 'Dien tich lam viec', value: '432 x 406 mm' },
                                                                                                  ],
                                                                                                      desc: 'xTool D1 Pro la may khac laser diode cao cap, phu hop cho nguoi moi bat dau den chuyen nghiep.',
                                                                                                          features: ['Lap dat trong 10 phut', 'Khac va cat da vat lieu', 'Ho tro file SVG, PNG, DXF'],
                                                                                                            },
                                                                                                            };

                                                                                                            export default function ProductPage({ params }: { params: { slug: string } }) {
                                                                                                              const product = productData[params.slug] || productData['xtool-d1-pro'];
                                                                                                                return (
                                                                                                                    <>
                                                                                                                          <Navbar />
                                                                                                                                <main className="min-h-screen bg-white">
                                                                                                                                        <div className="max-w-7xl mx-auto px-4 lg:px-8 py-8">
                                                                                                                                                  <nav className="text-sm text-gray-500 mb-8">
                                                                                                                                                              <Link href="/" className="hover:text-blue-600">Trang chu</Link>
                                                                                                                                                                          <span className="mx-2">/</span>
                                                                                                                                                                                      <Link href="/danh-muc" className="hover:text-blue-600">San pham</Link>
                                                                                                                                                                                                  <span className="mx-2">/</span>
                                                                                                                                                                                                              <span className="text-gray-900">{product.name}</span>
                                                                                                                                                                                                                        </nav>
                                                                                                                                                                                                                                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
                                                                                                                                                                                                                                              <div className="bg-gray-50 rounded-2xl p-8 flex items-center justify-center min-h-96">
                                                                                                                                                                                                                                                            <img src={product.img} alt={product.name} className="max-w-full max-h-96 object-contain"
                                                                                                                                                                                                                                                                            onError={(e) => { (e.target as HTMLImageElement).src = 'https://placehold.co/400x400/f3f4f6/9ca3af?text=' + encodeURIComponent(product.name); }} />
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                  <h1 className="text-3xl font-bold text-gray-900 mb-2">{product.name}</h1>
                                                                                                                                                                                                                                                                                                                                <p className="text-gray-500 text-lg mb-4">{product.tagline}</p>
                                                                                                                                                                                                                                                                                                                                              <p className="text-gray-600 leading-relaxed mb-6">{product.desc}</p>
                                                                                                                                                                                                                                                                                                                                                            <div className="text-2xl font-bold text-blue-600 mb-6">{product.price}</div>
                                                                                                                                                                                                                                                                                                                                                                          <div className="flex gap-3 mb-8">
                                                                                                                                                                                                                                                                                                                                                                                          <Link href="/lien-he" className="flex-1 bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 rounded-lg text-center">Nhan Tu Van</Link>
                                                                                                                                                                                                                                                                                                                                                                                                          <a href="tel:0901234567" className="flex-1 border-2 border-blue-600 text-blue-600 font-semibold py-3 rounded-lg text-center">Goi Ngay</a>
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-gray-50 rounded-xl p-5 mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3 className="font-bold text-gray-900 mb-4">Thong So Ky Thuat</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {product.specs.map((spec: any) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={spec.label} className="flex justify-between text-sm py-2 border-b border-gray-100 last:border-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-gray-500">{spec.label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="font-medium text-gray-900">{spec.value}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ul className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {product.features.map((f: string) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li key={f} className="flex items-center gap-2 text-sm text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-green-500">check</span>{f}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Footer />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }